# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lcbc12's bookmark
email: gicquelucas.pro@gmail.com
description: To keep an eye on my project updates!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Lcbc12.github.io/" # the base hostname & protocol for your site
github_username:  Lcbc12

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag